#!/bin/sh
# YouTerm by Jerry Bezencon, pdq 2013.
# Requirements: VLC Media Player

bold=`tput bold`
normal=`tput sgr0`
clear
echo "${bold}************************************************"
echo "YouTerm - Watch Youtube videos without a browser"
echo "************************************************${normal}"
echo ""


youterm_url() {
  echo -n "Input the url: "
	read url

	if [ "$url" = "" ]; then
		youterm_url
	fi
	
	echo ""
}

youterm_res() {
	echo "[1] 240p"
	echo "[2] 360p"
	echo "[3] 480p"
	echo "[4] 720p"
	echo "[5] 1080p"
	echo "[6] Exit"

	echo -n "Enter your menu choice [1-6]: "
	read res

	if [ "$res" = "" ]; then
		youterm_res
	fi

	case $res in

		1) vlc --preferred-resolution "240p" $url ;;
		2) vlc --preferred-resolution "360p" $url ;;
		3) vlc --preferred-resolution "480p" $url ;;
		4) vlc --preferred-resolution "720p" $url ;;
		5) vlc --preferred-resolution "1080p" $url ;;
		6) exit 6 ;;
		*) youterm_res ;;

	esac

}

while true
do
	  youterm_url
    youterm_res
    exit 0
done
